name = "bili-up-monitor"
main = "worker.js"
compatibility_date = "2024-09-01"
workers_dev = true

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "BILI_MONITOR_KV"
id = "b1323de1990543029f152c6e82010509"
